In [71]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
import os

In [72]:
os.getcwd()

'C:\\Users\\hp\\7.Muffassil_Project\\3_Wafer_fault_detection\\3_Muffassil_code'

In [73]:
# read file 
df=pd.read_csv('main_data.csv')
df.head()

,Unnamed: 0,wafer,Sensor-1,Sensor-2,Sensor-3,Sensor-4,Sensor-5,Sensor-6,Sensor-7,Sensor-8,...,Sensor-582,Sensor-583,Sensor-584,Sensor-585,Sensor-586,Sensor-587,Sensor-588,Sensor-589,Sensor-590,Good/Bad
0,0,Wafer-1201,3045.98,2544.85,2253.3444,1873.8678,1.1691,100.0,94.9722,0.1210,...,NaN,0.4948,0.0123,0.0033,2.4804,0.0291,0.0102,0.0033,35.0279,-1
1,1,Wafer-1202,3151.98,2563.75,2175.2556,1022.1660,1.2833,100.0,100.6222,0.1250,...,NaN,0.5063,0.0113,0.0031,2.2284,0.0291,0.0102,0.0033,35.0279,-1
2,2,Wafer-1203,3071.18,2489.86,2195.3000,1151.8233,0.9220,100.0,103.5467,0.1232,...,NaN,0.5033,0.0112,0.0029,2.2320,0.0291,0.0102,0.0033,35.0279,-1
3,3,Wafer-1204,2958.46,2523.78,2171.8556,1156.6018,1.4025,100.0,100.1367,0.1243,...,NaN,0.4954,0.0136,0.0033,2.7511,0.0291,0.0102,0.0033,35.0279,-1
4,4,Wafer-1205,3196.21,2413.39,2255.5222,1763.0739,1.2226,100.0,101.5878,0.1200,...,353.8319,0.5058,0.0094,0.0026,1.8673,0.0053,0.0188,0.0057,353.8319,-1

In [74]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 837 entries, 0 to 836
Columns: 593 entries, Unnamed: 0 to Good/Bad
dtypes: float64(577), int64(15), object(1)
memory usage: 3.8+ MB

In [75]:
df.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
Unnamed: 0,837.0,418.000000,241.765382,0.0000,209.000000,418.0000,627.00000,836.0000
Sensor-1,836.0,3020.762560,80.110713,2770.4000,2970.750000,3014.2900,3061.62500,3356.3500
Sensor-2,834.0,2495.829916,71.607771,2233.2900,2452.182500,2499.7350,2537.67500,2846.4400
Sensor-3,824.0,2200.208587,30.926326,2060.6600,2184.213875,2202.1889,2216.50000,2315.2667
Sensor-4,824.0,1474.891287,530.078688,0.0000,1110.206750,1298.4309,1751.83485,3715.0417
...,...,...,...,...,...,...,...,...
Sensor-587,837.0,0.023074,0.013394,-0.0169,0.015300,0.0218,0.02780,0.1028
Sensor-588,837.0,0.015922,0.009087,0.0032,0.009800,0.0145,0.01930,0.0799
Sensor-589,837.0,0.005121,0.003061,0.0010,0.003200,0.0045,0.00600,0.0286
Sensor-590,837.0,91.393672,89.302699,0.0000,41.078200,65.4842,104.30340,737.3048
Good/Bad,837.0,-0.911589,0.411349,-1.0000,-1.000000,-1.0000,-1.00000,1.0000

In [76]:
df.isna().sum()

Unnamed: 0     0
wafer          0
Sensor-1       1
Sensor-2       3
Sensor-3      13
              ..
Sensor-587     0
Sensor-588     0
Sensor-589     0
Sensor-590     0
Good/Bad       0
Length: 593, dtype: int64

In [77]:
# remove unnamed column
df.drop(columns=['Unnamed: 0','wafer'], inplace=True)
df.head()

,Sensor-1,Sensor-2,Sensor-3,Sensor-4,Sensor-5,Sensor-6,Sensor-7,Sensor-8,Sensor-9,Sensor-10,...,Sensor-582,Sensor-583,Sensor-584,Sensor-585,Sensor-586,Sensor-587,Sensor-588,Sensor-589,Sensor-590,Good/Bad
0,3045.98,2544.85,2253.3444,1873.8678,1.1691,100.0,94.9722,0.1210,1.4752,0.0084,...,NaN,0.4948,0.0123,0.0033,2.4804,0.0291,0.0102,0.0033,35.0279,-1
1,3151.98,2563.75,2175.2556,1022.1660,1.2833,100.0,100.6222,0.1250,1.4536,-0.0110,...,NaN,0.5063,0.0113,0.0031,2.2284,0.0291,0.0102,0.0033,35.0279,-1
2,3071.18,2489.86,2195.3000,1151.8233,0.9220,100.0,103.5467,0.1232,1.4826,0.0136,...,NaN,0.5033,0.0112,0.0029,2.2320,0.0291,0.0102,0.0033,35.0279,-1
3,2958.46,2523.78,2171.8556,1156.6018,1.4025,100.0,100.1367,0.1243,1.4645,0.0001,...,NaN,0.4954,0.0136,0.0033,2.7511,0.0291,0.0102,0.0033,35.0279,-1
4,3196.21,2413.39,2255.5222,1763.0739,1.2226,100.0,101.5878,0.1200,1.4845,-0.0037,...,353.8319,0.5058,0.0094,0.0026,1.8673,0.0053,0.0188,0.0057,353.8319,-1

In [78]:
# task :
# use mean and median for null values

from sklearn.impute import KNNImputer
imputer=KNNImputer(n_neighbors=3,missing_values=np.nan)
new_df=imputer.fit_transform(df)

In [79]:
new_df=pd.DataFrame(new_df,columns=df.columns)
new_df

,Sensor-1,Sensor-2,Sensor-3,Sensor-4,Sensor-5,Sensor-6,Sensor-7,Sensor-8,Sensor-9,Sensor-10,...,Sensor-582,Sensor-583,Sensor-584,Sensor-585,Sensor-586,Sensor-587,Sensor-588,Sensor-589,Sensor-590,Good/Bad
0,3045.98,2544.85,2253.3444,1873.8678,1.1691,100.0,94.9722,0.1210,1.4752,0.0084,...,47.958333,0.4948,0.0123,0.0033,2.4804,0.0291,0.0102,0.0033,35.0279,-1.0
1,3151.98,2563.75,2175.2556,1022.1660,1.2833,100.0,100.6222,0.1250,1.4536,-0.0110,...,111.563900,0.5063,0.0113,0.0031,2.2284,0.0291,0.0102,0.0033,35.0279,-1.0
2,3071.18,2489.86,2195.3000,1151.8233,0.9220,100.0,103.5467,0.1232,1.4826,0.0136,...,83.487367,0.5033,0.0112,0.0029,2.2320,0.0291,0.0102,0.0033,35.0279,-1.0
3,2958.46,2523.78,2171.8556,1156.6018,1.4025,100.0,100.1367,0.1243,1.4645,0.0001,...,38.998500,0.4954,0.0136,0.0033,2.7511,0.0291,0.0102,0.0033,35.0279,-1.0
4,3196.21,2413.39,2255.5222,1763.0739,1.2226,100.0,101.5878,0.1200,1.4845,-0.0037,...,353.831900,0.5058,0.0094,0.0026,1.8673,0.0053,0.0188,0.0057,353.8319,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
832,3169.00,2265.60,2187.9889,1096.3790,0.9065,100.0,97.6567,0.1221,1.4109,-0.0239,...,73.633500,0.4912,0.0127,0.0039,2.5801,0.0166,0.0122,0.0036,73.6335,-1.0
833,2923.19,2516.40,2180.8889,1084.7221,0.9085,100.0,94.2467,0.1226,1.3137,0.0345,...,69.087633,0.4939,0.0163,0.0037,3.2914,0.0166,0.0122,0.0036,73.6335,-1.0
834,3003.43,2448.34,2205.5000,1287.3538,2.3842,100.0,111.7644,0.1241,1.4339,0.0020,...,80.579000,0.4966,0.0084,0.0020,1.6866,0.0166,0.0122,0.0036,73.6335,-1.0
835,2953.63,2500.05,2195.9778,1388.2869,1.5605,100.0,103.2400,0.1234,1.5177,0.0183,...,171.318300,0.5009,0.0135,0.0035,2.7038,0.0178,0.0305,0.0106,171.3183,-1.0
836,3034.74,2458.90,2192.1889,1435.9611,2.3870,100.0,107.3989,0.1229,1.5447,0.0036,...,368.893600,0.5008,0.0137,0.0033,2.7317,0.0048,0.0178,0.0055,368.8936,-1.0

In [80]:
new_df.isnull().sum()

Sensor-1      0
Sensor-2      0
Sensor-3      0
Sensor-4      0
Sensor-5      0
             ..
Sensor-587    0
Sensor-588    0
Sensor-589    0
Sensor-590    0
Good/Bad      0
Length: 591, dtype: int64

In [84]:
# checking the column which have a zero standard deviation
# new_df.describe()['Sensor-1']['std']

describe=new_df.describe()
drop_col=[]
for i in new_df.columns:
    if describe[i]['std']==0:
        drop_col.append(i)
print(drop_col)

['Sensor-6', 'Sensor-14', 'Sensor-43', 'Sensor-50', 'Sensor-53', 'Sensor-70', 'Sensor-98', 'Sensor-142', 'Sensor-150', 'Sensor-179', 'Sensor-180', 'Sensor-187', 'Sensor-190', 'Sensor-191', 'Sensor-192', 'Sensor-193', 'Sensor-194', 'Sensor-195', 'Sensor-227', 'Sensor-230', 'Sensor-231', 'Sensor-232', 'Sensor-233', 'Sensor-234', 'Sensor-235', 'Sensor-236', 'Sensor-237', 'Sensor-238', 'Sensor-241', 'Sensor-242', 'Sensor-243', 'Sensor-244', 'Sensor-257', 'Sensor-258', 'Sensor-259', 'Sensor-260', 'Sensor-261', 'Sensor-262', 'Sensor-263', 'Sensor-264', 'Sensor-265', 'Sensor-266', 'Sensor-267', 'Sensor-277', 'Sensor-285', 'Sensor-314', 'Sensor-315', 'Sensor-316', 'Sensor-323', 'Sensor-326', 'Sensor-327', 'Sensor-328', 'Sensor-329', 'Sensor-330', 'Sensor-331', 'Sensor-365', 'Sensor-370', 'Sensor-371', 'Sensor-372', 'Sensor-373', 'Sensor-374', 'Sensor-375', 'Sensor-376', 'Sensor-379', 'Sensor-380', 'Sensor-381', 'Sensor-382', 'Sensor-395', 'Sensor-396', 'Sensor-397', 'Sensor-398', 'Sensor-399', 'Sensor-400', 'Sensor-401', 'Sensor-402', 'Sensor-403', 'Sensor-404', 'Sensor-405', 'Sensor-415', 'Sensor-423', 'Sensor-450', 'Sensor-451', 'Sensor-452', 'Sensor-459', 'Sensor-462', 'Sensor-463', 'Sensor-464', 'Sensor-465', 'Sensor-466', 'Sensor-467', 'Sensor-482', 'Sensor-499', 'Sensor-502', 'Sensor-503', 'Sensor-504', 'Sensor-505', 'Sensor-506', 'Sensor-507', 'Sensor-508', 'Sensor-509', 'Sensor-510', 'Sensor-513', 'Sensor-514', 'Sensor-515', 'Sensor-516', 'Sensor-529', 'Sensor-530', 'Sensor-531', 'Sensor-532', 'Sensor-533', 'Sensor-534', 'Sensor-535', 'Sensor-536', 'Sensor-537', 'Sensor-538', 'Sensor-539']

In [87]:
new_df.drop(columns=drop_col,inplace=True, axis=1)

In [88]:
new_df.head()

,Sensor-1,Sensor-2,Sensor-3,Sensor-4,Sensor-5,Sensor-7,Sensor-8,Sensor-9,Sensor-10,Sensor-11,...,Sensor-582,Sensor-583,Sensor-584,Sensor-585,Sensor-586,Sensor-587,Sensor-588,Sensor-589,Sensor-590,Good/Bad
0,3045.98,2544.85,2253.3444,1873.8678,1.1691,94.9722,0.1210,1.4752,0.0084,0.0009,...,47.958333,0.4948,0.0123,0.0033,2.4804,0.0291,0.0102,0.0033,35.0279,-1.0
1,3151.98,2563.75,2175.2556,1022.1660,1.2833,100.6222,0.1250,1.4536,-0.0110,-0.0035,...,111.563900,0.5063,0.0113,0.0031,2.2284,0.0291,0.0102,0.0033,35.0279,-1.0
2,3071.18,2489.86,2195.3000,1151.8233,0.9220,103.5467,0.1232,1.4826,0.0136,0.0009,...,83.487367,0.5033,0.0112,0.0029,2.2320,0.0291,0.0102,0.0033,35.0279,-1.0
3,2958.46,2523.78,2171.8556,1156.6018,1.4025,100.1367,0.1243,1.4645,0.0001,0.0067,...,38.998500,0.4954,0.0136,0.0033,2.7511,0.0291,0.0102,0.0033,35.0279,-1.0
4,3196.21,2413.39,2255.5222,1763.0739,1.2226,101.5878,0.1200,1.4845,-0.0037,0.0049,...,353.831900,0.5058,0.0094,0.0026,1.8673,0.0053,0.0188,0.0057,353.8319,-1.0

In [100]:
new_df.to_csv('clean_data.csv', index=False)

In [104]:

# feature scaling 
X=new_df.iloc[:,:-1]
y=new_df.iloc[:,[-1]]

In [105]:
X.head()

,Sensor-1,Sensor-2,Sensor-3,Sensor-4,Sensor-5,Sensor-7,Sensor-8,Sensor-9,Sensor-10,Sensor-11,...,Sensor-581,Sensor-582,Sensor-583,Sensor-584,Sensor-585,Sensor-586,Sensor-587,Sensor-588,Sensor-589,Sensor-590
0,3045.98,2544.85,2253.3444,1873.8678,1.1691,94.9722,0.1210,1.4752,0.0084,0.0009,...,0.004233,47.958333,0.4948,0.0123,0.0033,2.4804,0.0291,0.0102,0.0033,35.0279
1,3151.98,2563.75,2175.2556,1022.1660,1.2833,100.6222,0.1250,1.4536,-0.0110,-0.0035,...,0.007500,111.563900,0.5063,0.0113,0.0031,2.2284,0.0291,0.0102,0.0033,35.0279
2,3071.18,2489.86,2195.3000,1151.8233,0.9220,103.5467,0.1232,1.4826,0.0136,0.0009,...,0.004733,83.487367,0.5033,0.0112,0.0029,2.2320,0.0291,0.0102,0.0033,35.0279
3,2958.46,2523.78,2171.8556,1156.6018,1.4025,100.1367,0.1243,1.4645,0.0001,0.0067,...,0.003967,38.998500,0.4954,0.0136,0.0033,2.7511,0.0291,0.0102,0.0033,35.0279
4,3196.21,2413.39,2255.5222,1763.0739,1.2226,101.5878,0.1200,1.4845,-0.0037,0.0049,...,0.005700,353.831900,0.5058,0.0094,0.0026,1.8673,0.0053,0.0188,0.0057,353.8319

In [106]:
y.head()

   Good/Bad
0      -1.0
1      -1.0
2      -1.0
3      -1.0
4      -1.0

In [107]:
from sklearn.preprocessing import StandardScaler
scale=StandardScaler()
X_sc=scale.fit_transform(X)

In [108]:
X_sc=pd.DataFrame(X_sc,columns=X.columns)
X_sc.head()

,Sensor-1,Sensor-2,Sensor-3,Sensor-4,Sensor-5,Sensor-7,Sensor-8,Sensor-9,Sensor-10,Sensor-11,...,Sensor-581,Sensor-582,Sensor-583,Sensor-584,Sensor-585,Sensor-586,Sensor-587,Sensor-588,Sensor-589,Sensor-590
0,0.314873,0.686297,1.716533,0.751753,-0.072293,-0.639816,-0.008131,0.333847,0.556910,0.146148,...,-0.409533,-0.708648,-1.581698,-0.166817,-0.130635,-0.155417,0.450143,-0.630063,-0.595055,-0.631554
1,1.639583,0.950704,-0.820418,-0.860566,-0.070803,0.095549,0.289061,0.060253,-0.761016,-0.347297,...,0.838325,0.229221,1.950290,-0.227418,-0.186508,-0.228579,0.450143,-0.630063,-0.595055,-0.631554
2,0.629804,-0.083003,-0.169215,-0.615118,-0.075516,0.476181,0.155325,0.427578,0.910168,0.146148,...,-0.218534,-0.184770,1.028902,-0.233478,-0.242380,-0.227534,0.450143,-0.630063,-0.595055,-0.631554
3,-0.778888,0.391531,-0.930877,-0.606072,-0.069248,0.032359,0.237053,0.198316,-0.006945,0.796597,...,-0.511399,-0.840762,-1.397420,-0.088035,-0.130635,-0.076826,0.450143,-0.630063,-0.595055,-0.631554
4,2.192337,-1.152804,1.787285,0.542014,-0.071595,0.221224,-0.082429,0.451644,-0.265095,0.594734,...,0.150730,3.801483,1.796725,-0.342560,-0.326188,-0.333415,-1.327777,0.316946,0.189345,2.940506

In [109]:
new_df['Good/Bad'].value_counts()

-1.0    800
 1.0     37
Name: Good/Bad, dtype: int64